---
- hosts: wip
  gather_facts: no

  tasks:
  - name: Get netstat interfaces
    command:
      /usr/bin/netstat -ni
    register: netstat_ni
    changed_when: false
   
  - name: Get netstat routes
    command:
      /usr/bin/netstat -nr
    register: netstat_nr
    changed_when: false
   
  - name: Display results
    debug:
      var: "{{ item }}.stdout_lines"
    with_items:
      - netstat_ni
      - netstat_nr
