---
# Example to get PID and use it in the playbook.
- hosts: wip
  gather_facts: no

  tasks:
    - name: GET ps output
      command: ps -f
      register: ansible_ps
    - name: COMMAND the pid
      command: 'echo $PPID'
      register: ansible_pid_c
    - name: SHELL the pid
      shell: 'echo $PPID'
      register: ansible_pid_s
    - name: Display ps
      debug:
        msg: "{{ ansible_ps.stdout.split(\"\n\") }}"
    - name: Display PID command
      debug:
        var: ansible_pid_c
    - name: Display PID shell
      debug:
        var: ansible_pid_s
