# Interface `/usr/lpp/bos.sysmgt/nim/methods/c_sm_nim cust ...` in a playbook
# e.g.,  /usr/lpp/bos.sysmgt/nim/methods/c_sm_nim cust  -l 'aixtools' \
#        -o 'aixtools.gnu.bash' -f '' -f '' -f 'Y' -f 'c' -f 'N' \
#        -f 'g' -f 'X' -f '' -f ''

# /usr/sbin/nimclient -o showres
#              -a sm_inst_flags="installp_cmd -f bash,aixtools.python -L -l" \
#              -a resource=710404_lpp
#I:aixtools.python.py36.adt 3.6.12.0
#I:aixtools.python.py36.man.en_US 3.6.12.0
#I:aixtools.python.py36.rte 3.6.12.0
#R:bash-5.0-1 5.0-1

# The output - when successful ALWAYS has a letter : as prefix,
# i.e, the second lettter is always a colon ':'
# this can be used in a when: statement later

---
- hosts: wip
  gather_facts: no

  tasks:
  - name: Verify existence in repository
    command: >
      nimclient -o showres
        -a sm_inst_flags="installp_cmd -f aixtools.gnu.bash -L -l"
        -a resource=aixtools
    register: showres
    # This only checks the first line of output, that should be enough
    # to fail the play
    failed_when: showres.stdout[1] != ':'

  # Maybe not the best way - yet. Looks clumsy
  - name: Display results
    debug:
      var: showres.stdout_lines


  # INST_LIST="-f${TMP_LIST}"
  - name: Install the software.
    command: >
      /usr/sbin/nimclient -o cust -a lpp_source=aixtools
            -a filesets="aixtools.gnu.bash"
            -a installp_flags="-agX"
    register: cust

  - fail:
      msg: "STDERR is: {{ cust.stderr_lines }}"
    when: cust.stderr|length > 0

  # Maybe not the best way - yet. Looks clumsy
  - name: Display (preview) results
    debug:
      msg: " SUCCESS: {{ cust.stdout.split(\"\n\") }}"
    when: cust.stderr|length == 0
