---
- hosts: wip
  gather_facts: no

  tasks:
  - name: Showres example
    command: >
      nimclient -o showres
        -a sm_inst_flags="installp_cmd -f bos,aixtools -L -l"
        -a resource=710404_lpp
    register: showres

  # Maybe not the best way - yet. Looks clumsy
  - name: Display results
    debug:
      msg: "{{ showres.stdout.split(\"\n\") }}"


