# Playbook to show working with variables - especially dictionaries
---
- hosts: localhost
  gather_facts: yes

  vars_files:
    - vars/bash.yml

  vars:
    - myfacts: "{{ ansible_facts.vgs }}"
    - mysys0: "{{ ansible_facts.ansible_devices.sys0 }}"
    - pkgs: "{{ packages }}"
    - pkg: pkgs[0]
    - pname: pkgs['name']

  tasks:
    # working bits
    - name: "Show ansible_facts value"
      debug:
        var: ansible_facts
    - name: "Show localized myfacts value"
      debug:
        var: myfacts
    - name: "Show localized mysys0 value"
      debug:
        var: mysys0
    - name: "Show var/bash.yml packages value"
      debug:
        var: packages
    - name: "Show localized pkgs var value"
      debug:
        var: pkgs
    - name: "Show localized pkg var value"
      debug:
        var: pkg
    - name: "Show localized pname var value"
      debug:
        var: pname

    - name: "Show vars for further debugging"
      debug:
        var: vars
      ignore_errors: yes
