---
- hosts: wip
  gather_facts: no

  tasks:
  # Remove the interface from the ODM - and then
  # recreate - empty -  using cfgmgr
  - name: remove the en1 interface definition
    command:
      rmdev -dl en1
  - name: call cfgmgr
    command:
      cfgmgr
