# Playbook to clear and renew ssh-keys in knownhosts locally
# And then use the new/renewed keys to set an IP address on en1
# Gather_facts is no: not relevant at this stage (of development)
---
- hosts: localhost
  gather_facts: no

  vars_files:
    - ./vars/knownhosts.yml

  tasks:
  - name: Remove ssh key for OSUtest
    command:
       ssh-keygen -R "{{ item }}"
    with_items: "{{ known_hosts }}"
  - name: add new keys for OSUtest
    command:
       ssh -o StrictHostKeyChecking=accept-new root@"{{ item }}" date
    with_items: "{{ known_hosts }}"
